backend:
  name: github
  repo: dbeod2/blog
  branch: main

media_folder: /content/images
public_folder: /content/images

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "Title" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "author", label: "Author", default: "ura", widget: "hidden" }
      - { name: "hero_image", label: "Hero_image", widget: "file", default: "/content/images/unnamed.jpg" }
      - { name: "body", label: "Body", widget: "markdown" }